#!/usr/bin/env zsh

DIR="$(pwd)"

function ensure_link {
    test -L "$HOME/$2" || ln -s "$DIR/$1" "$HOME/$2"
}

ensure_link "configs/zshrc"         ".zshrc"
ensure_link "configs/zshenv"        ".zshenv"
ensure_link "configs/gitconfig"     ".gitconfig"
ensure_link "configs/emacs.d"       ".emacs.d"
ensure_link "configs/prettierrc"    ".prettierrc"
