#+TITLE: So you want to see my dotfiles ehhh?
#+AUTHOR: venikx
#+STARTUP: hideblocks

* Installation
Use at own risk!

1. ~cd ~~
2. Clone: git clone git@gitlab.com:venikx/dotfiles.git
3. Dry-run: ~stow -vnS --adopt compton dmenu emacs git gpg i3 ranger shell web x~
   DISCLAIMER: The ~--adopt~ flag is slightly abused here, since it's meant to bring change back from
   outside ~stow~ into the repo again. However I think it's valuable when a new system is installed to
   review the changes between the existing dotfiles and the ones overwritten by the system.

   There's potential to adopt some of the code, but most likely you'll discard the
   changes. Important thing to note is that the links are then made! :)
4. Run ~stow -vS --adopt compton dmenu emacs git gpg i3 ranger shell web x~
5. Review the possible changes in the dotfiles

* Improvements
** TODO Use ~stow~ to target and manage specific OS configurations
** TODO Use ~stow~ to manage the ~.password-store~
- Setting up the yubikey and generating the keys: https://github.com/drduh/YubiKey-Guide
- Using gpg to generate a public ssh key: https://suva.sh/posts/gpg-ssh-smartcard-yubikey-keybase/#using-the-gpg-and-ssh-keys
- QR-code as an alternative back-up method: ????
- Paperkeys as a last resort: https://github.com/drduh/YubiKey-Guide
