{ config, lib, pkgs, ... }:

{
  home.sessionVariables = {
    ZDOTDIR = "$XDG_CONFIG_HOME/zsh";
    ZSH_CACHE = "$XDG_CACHE_HOME/zsh";
  };

  programs.zsh = {
    enable = true;
    enableAutosuggestions = true;
    enableCompletion = true;
    syntaxHighlighting = { enable = true; };
    enableVteIntegration = true;
    autocd = true;
    cdpath = [ "~/code" ];
    defaultKeymap = "viins";
    #dirHashes = {};
    dotDir = ".config/zsh";
    historySubstringSearch.enable = true;
    history = {
      expireDuplicatesFirst = true;
      extended = true;
      ignoreSpace = true;
      path = "${config.xdg.dataHome}/zsh/zsh_history";
    };

    initExtraBeforeCompInit = ''
      # KEYBINDINGS
      # Shift-Tab when Completion is active
      bindkey -M viins '^[[Z' reverse-menu-complete

      # FUNCTION ALIASES
      zman() {
        PAGER="less -g -I -s '+/^       "$1"'" man zshall;
      }

      # COMPLETION
      source ${./completion.zsh}
    '';

    initExtraFirst = ''
      # This file was autogenerated, do not edit it!

      source ${./config.zsh}
    '';
    #prezto = {
    #  enable = false;
    #};
    shellAliases = {
      mkdir = "mkdir -p";
      wget = "wget -c";
      gurl = "curl --compressed";
    };
  };

  programs.fzf = {
    enable = true;
    enableZshIntegration = true;
    defaultOptions = [ "--reverse" "--ansi" ];
    defaultCommand = "fd .";
    fileWidgetCommand = "fd .";
    changeDirWidgetCommand = "fd --type d . $HOME";
  };

  programs.eza = {
    enable = true;
    enableAliases = true;
  };

  home.packages = with pkgs; [ bat fd tldr ];
}
