# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usb_storage" "usbhid" "sd_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    kernelPackages = pkgs.linuxPackages_latest;
    extraModulePackages = [ ];
    # kernelParams = [ "nomodeset" ];
  };

  modules.hardware = {
    audio.enable = true;
    bluetooth.enable = true;
    bluetooth.audio.enable = true;
    amd.enable = true;
  };

  # CPU
  hardware.cpu.amd.updateMicrocode = true;
  # Power Management
  environment.systemPackages = [ pkgs.acpi ];
  powerManagement.powertop.enable = true;
  services.tlp.enable = true;
  # Monitor backlight control
  programs.light.enable = true;
  users.users.venikx = {
    extraGroups = [ "video" ];
  };
  # SSD
  services.fstrim.enable = lib.mkDefault true;

  fileSystems = {
    "/" =
      { device = "/dev/disk/by-uuid/da357781-e455-4df0-b3fe-ecafb3077280";
        fsType = "ext4";
      };

    "/boot" =
      { device = "/dev/disk/by-uuid/2CE1-F5B3";
        fsType = "vfat";
      };
  };
  swapDevices = [ ];

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "20.09"; # Did you read the comment?
}
